
server:
  port: 8000

check:
  check-application.yml

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://10.110.248.148:8761/eureka

spring:
  application:
    name: apigateway-service
#  rabbitmq:
#    host: 172.10.40.152
#    port: 5672
#    username: guest
#    password: guest
  config:
    import: classpath:/bootstrap.yml

management:
  endpoints:
    web:
      exposure:
        include: "*"
