
server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka # ??? ? ??

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        - id: counter-service
          uri: lb://COUNTER-SERVICE
          predicates:
            - Path=/counter-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/counter-service(?<segment>.*), /$\{segment}
        - id: store-service
          uri: lb://STORE-SERVICE
          predicates:
            - Path=/store-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/store-service(?<segment>.*), /$\{segment}
token:
  expiration_time: 86400000
