
server:
  port: 8000

#  rabbitmq:
#    host: 172.10.40.152
#    port: 5672
#    username: guest
#    password: guest


management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh
spring:
  application:
    name: apigateway-service
  config:
    import: classpath:/bootstrap-local.yml
check:
  check-application.yml

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka