
server:
  port: 8080

spring:
  application:
    name: counter-service
  rabbitmq:
    host: 172.10.40.152
    port: 5672
    username: guest
    password: guest
  config:
    import: classpath:/bootstrap.yml


   # config test
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.10.40.43:30306/counterdb
    username: root
    password: rlaxogjs8312

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
      show_sql: true
      format_sql: true
    open-in-view: true

# ZIPKIN 설정
management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3_MULTI
  zipkin:
    tracing:
      endpoint: "http://172.10.40.174:30100/api/v2/spans"
  endpoints:
    web:
      exposure:
        include:
          refresh, health, beans, busrefresh
logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"
