
server:
  port: 0

spring:
  application:
    name: counter-service
  rabbitmq:
    host: 172.10.40.152
    port: 5672
    username: guest
    password: guest
  config:
    import: classpath:/bootstrap-local.yml
