server:
  port: 8080

spring:
  application:
    name: user-service
  rabbitmq:
    host: 172.10.40.152
    port: 5672
    username: guest
    password: guest
  config:
    import: classpath:/bootstrap.yml

counter_service:
  url: http://COUNTER-SERVICE/counter-service/%s/orders #http://127.0.0.1:8000/order-service/%s/orders
  exception:
    orders_is_empty: no item

logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"