server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 172.10.40.152
    port: 5672
    username: guest
    password: guest
  config:
    import: classpath:/bootstrap.yml
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: file://${user.home}/Desktop/native-file-repo #file://root/native-file-repo
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jake-huen/spring-cloud-config
          username: Jake-huen
          password: rlaxogjs8312@

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh