server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  config:
    import: classpath:/bootstrap.yml
#  profiles:
#    active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jake-huen/spring-cloud-config
          username: Jake-huen
          password: rlaxogjs8312@

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httptrace, busrefresh