
server:
  port: 8080

spring:
  application:
    name: store-service
  rabbitmq:
    host: 172.10.40.152
    port: 5672
    username: guest
    password: guest
  config:
    import: classpath:/bootstrap.yml
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true

# ZIPKIN 설정
management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      consume: B3
      produce: B3_MULTI
  zipkin:
    tracing:
      endpoint: "http://172.10.40.174:30100/api/v2/spans"
  endpoints:
    web:
      exposure:
        include:
          refresh, health, beans, busrefresh
logging:
  pattern:
    level: "%5p [%X{traceId:-},%X{spanId:-}]"