
server:
  port: 8761

spring:
  application:
    name: discoveryservice
#  cloud:
#    config:
#      uri: http://config-server:8888
#      name: discovery-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false